name: Update translations and documentation
on:
  workflow_dispatch:
  schedule:
    - cron:  '42 3 * * 1'

jobs:

  update_transifex_docs:
    runs-on: ubuntu-latest
    name: Update translations and documentation
    steps:
      - uses: actions/checkout@5c3ccc22eb2c950a0fa5bc7c47190d8e3f7e681a # v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v2
        with:
          go-version: ^1.18.4
      - run: |
          set -euo pipefail
          git config --global user.name 'Syncthing Release Automation'
          git config --global user.email 'release@syncthing.net'
          bash build.sh translate
          bash build.sh prerelease
          git push
        env:
          TRANSIFEX_USER: ${{ secrets.TRANSIFEX_USER }}
          TRANSIFEX_PASS: ${{ secrets.TRANSIFEX_PASS }}
